spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geekbrains
    username: postgres
    password: user
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml